### ISSUE TITLE
depends on deprecated serde_yaml (maybe move to serde_yml?)

### ISSUE THREAD

**Issue by dkg** [rust-cli/confy#103]
I noticed that one of the dependencies for `confy` is the `serde_yaml` crate which has been explicitly deprecated as unmaintained upstream.  Perhaps confy should switch to `serde_yml` or something similar instead, for its yaml support?

**Comment by Zykino** [comment]
Already discussed in #100

**Comment by deg4uss3r** [comment]
Hello! Yes as @Zykino mentioned I address this in #100. For completeness I'll also add my thoughts here. 

I want to keep our current crate for a couple reasons.

1. We have had that crate the entire length of this project and have had no issues
2. The updated [`serde_yml`](https://github.com/sebastienrousseau/serde_yml) is still under a sole maintainer
3. The `yaml` spec in its lifetime won't benefit much from moving the crate (e.g. there won't be new features or changes to `yaml`)
4. We now have a reoccurring audit job to warn us of any vulnerabilities (and in addition other unmaintained crates, as tradition is not good practice)

The last point being the most important, if the audit job uncovers anything with `serde_yaml` then we'd move immediately. 

However, if any thing changes or that crate does end up getting significant feature updates that are attractive to this library we can reopen this issue and consider.
