### ISSUE TITLE
Release planned?

### ISSUE THREAD

**Issue by moridius** [rust-cli/confy#22]
Is there any plan to make a release? Things like #8 are fixed but not on crates.io yet, which IMHO makes this great library unusable.

**Comment by Dylan-DPC** [comment]
Yes we do. Waiting for #17 to be merged then i'll release a new version

**Comment by moridius** [comment]
Thanks, that's great news!

**Comment by getreu** [comment]
Please publish an intermediate release soon! My crate `tp-note` depends on yours. As your last version 0.3.1 panics, when fields in the configuration file are missing, my crate does so also. For my crate it is a blocker.

**Comment by Dylan-DPC** [comment]
0.4 is now released. Thanks and sorry for the delay :)

**Comment by getreu** [comment]
Thank you. Your quick help allowed me to release [Releases · getreu/tp-note](https://github.com/getreu/tp-note/releases).
