### ISSUE TITLE
Please release quickly after commiting bugfix

### ISSUE THREAD

**Issue by getreu** [rust-cli/confy#26]
Thank you for this little, but very useful crate.

#12 fixes a blocker: confy should never panic confronted to erroneous configuration files.

Unfortunately version 0.3.1, the last published on crates.io, comes without bug-fix and panics!
As a result my crate [getreu/tp-note: fast note-taking with templates and filename synchronization](https://github.com/getreu/tp-note) also panics. This is a blocker for Windows user!

Please release immediately when a bug-fix is available and tested. I tested your last commit 5a58388fa9b8bcd790a62c2a9db5abdcbe9fb467 and it works well.

**Comment by Dylan-DPC** [comment]
hi. I'm very sorry about this. will look into releasing a new version today. thanks

**Comment by getreu** [comment]
Thank you.

**Comment by Dylan-DPC** [comment]
@getreu 0.4 is now available :)

**Comment by getreu** [comment]
Thank you. With you quick help, I could [release tp-note v1.0.0](https://github.com/getreu/tp-note/releases/tag/v1.0.0) yesterday.
