### ISSUE TITLE
Custom Name for Config Files

### ISSUE THREAD

**Issue by strix** [rust-cli/confy#30]
First of all, I love the convenience that this package provides but I ran into a problem that might have a simple solution.
I want to have multiple config files per project. For example, I would like to store/load the following files on Linux:
```
~/.config/app-name/config1.toml
~/.config/app-name/config2.toml
~/.config/app-name/config3.toml
```
With confy's current functionality I can only generate a `~/.config/app-name/app-name.toml` file but I'd like to have multiple configs per project.

I've got a [quick solution](https://github.com/strix/confy/commit/fb60e8a7e50877527d4039df96abf04a64e451b1) working for me on a fork but it would be nice if this kind of functionality could be in the official package.

**Comment by matthiasbeyer** [comment]
Why can't you use the `load()` [function](https://docs.rs/confy/0.4.0/confy/fn.load.html) with `load("config1")`, `load("config2")` and so on?

**Comment by strix** [comment]
> Why can't you use the `load()` [function](https://docs.rs/confy/0.4.0/confy/fn.load.html) with `load("config1")`, `load("config2")` and so on?

Doing that (on Linux) would result in:
```
~/.config/config1/config1.toml
~/.config/config2/config2.toml
```
This happens because the `name` parameter is being used for both [retrieving the config](https://docs.rs/confy/0.4.0/src/confy/lib.rs.html#103) path (using [ProjectDirs::from](https://docs.rs/directories/2.0.2/directories/struct.ProjectDirs.html#method.from))  _and_ to [set the file name](https://docs.rs/confy/0.4.0/src/confy/lib.rs.html#107).

**Comment by matthiasbeyer** [comment]
Ah. Sure. Did not read the code close enough. Well, I'm not sure about the others, but I'd love to see a patch for that usecase.

**Comment by deg0nz** [comment]
I have the exact same use case. It would be nice to have a comment by the maintainers if this behaviour is wanted or not; since it could/would add more complexity to the usage of the API and the goal of this crate is to make configs as easy as possible.
