### ISSUE TITLE
Yaml does not work

### ISSUE THREAD

**Issue by ShayBox** [rust-cli/confy#32]
![image](https://user-images.githubusercontent.com/9505196/85811683-ccc30b80-b72c-11ea-912a-2be8fe3bce82.png)

**Comment by Restioson** [comment]
What version is the dependency for?

**Comment by Restioson** [comment]
Looks like 0.4.0 is a bit out of date. Probably needs an update pushed to crates.io

**Comment by reflog** [comment]
@ShayBox - this worked for me:
```
[dependencies.confy]
version = "0.4.0"
features = ["yaml_conf"]
default-features = false

[patch.crates-io]
confy = { git = 'https://github.com/rust-cli/confy' }
```

**Comment by jjmark15** [comment]
is there any intention to fix this any time soon?

**Comment by Restioson** [comment]
I think it's fixed, but confy needs a version bump to 0.5 and crates.io release.

**Comment by leethomas** [comment]
I see 0.5.0 mentioned in the README, but it appears that 0.5.0 hasn't been released yet. Is there a timeline on when it might get published?

**Comment by Kerwood** [comment]
Is this project still alive ?

**Comment by deg4uss3r** [comment]
closing, please reopen if this is still broken.
