### ISSUE TITLE
Update directories crate (and others ?) before next version

### ISSUE THREAD

**Issue by Zykino** [rust-cli/confy#38]
The `directories` crate has a breaking change when upgrading to version 3 (specifically macOS change). https://github.com/dirs-dev/directories-rs#3
I did not check more, but I will before making a PR.

**Comment by matthiasbeyer** [comment]
Thanks for reporting this! This might have an influence on our release number as well (0.5.0 instead of 0.4.1 or something like that).

**Comment by Zykino** [comment]
I think next version should be 0.5.0 anyway since yaml was added. But maybe adding a feature does not requires bumping the "major" revision ?
Anyway #37 add an "optional" parameter and so change the definition of `load` and `store`.

**Comment by matthiasbeyer** [comment]
> But maybe adding a feature does not requires bumping the "major" revision ?

As we are in 0.x.y, we only should bump the minor version, not the major.

**Comment by Dylan-DPC** [comment]
yeah directories-next is a change of behaviour, so it makes sense to propagate this change downstream so it makes sense to have a major (0.5) release.
