### ISSUE TITLE
Confy corrupts config files

### ISSUE THREAD

**Issue by satarsa** [rust-cli/confy#53]
I use confy to store float values in toml. It was working fine until recently (a month ago?) instead of storing something like
```value = 0.0```
it is stored like
```value = --0.0```
and of course after restart confy returns an error on this value.
I understand that this is probably a bug in the toml crate (?) which has likely got a minor update which breaks confy, but I am not sure how to report the issue there.

**Comment by satarsa** [comment]
I found that it happens only if f64 is -0.0 (i.e 0b10000....), if it helps.

**Comment by AlyoshaVasilieva** [comment]
Fixed in https://github.com/alexcrichton/toml-rs/pull/426 (not released to crates.io)

**Comment by AlyoshaVasilieva** [comment]
Now released: https://github.com/alexcrichton/toml-rs/releases/tag/0.5.9

**Comment by satarsa** [comment]
> Now released: https://github.com/alexcrichton/toml-rs/releases/tag/0.5.9

Yep, thanks, can be closed, I guess.
