### ISSUE TITLE
🐛 Bad TOML data

### ISSUE THREAD

**Issue by segersniels** [rust-cli/confy#81]
Not sure if I'm just being stupid, but it looks like when you add config values after the original toml file has been created it errors with `Bad TOML data`. I would expect it to just use the specified default trait and use that instead.

**Comment by Kernald** [comment]
Curious as of why this has been closed? I'm hitting the same issue - overriding a single configuration option in the file results in a panic when reading it. I would expect confy to fall-back to default values.
