### ISSUE TITLE
Add `load_or_die` feature

### ISSUE THREAD

**Issue by samgj18** [rust-cli/confy#82]
Is there any chance to create a load_or_die feature such that application don't start if not able to find configuration file? I'd be happy to implement this given the opportunity.

**Comment by matthiasbeyer** [comment]
If you're using `anyhow` for example, you can do this:

```rust
#[derive(Default, Serialize, Deserialize)]
struct MyConfig {}

fn main() -> Result<(), anyhow::Error> {
    let cfg: MyConfig = confy::load("my-app-name", None)?;
    Ok(())
}
```

(Example taken from [`confy::load`](https://docs.rs/confy/latest/confy/fn.load.html))

**Comment by matthiasbeyer** [comment]
Does this solve your usecase?

**Comment by samgj18** [comment]
Hey. it does! Appreciate it!

**Comment by matthiasbeyer** [comment]
You're welcome! :+1:
