### ISSUE TITLE
Dependencies update?

### ISSUE THREAD

**Issue by daniestevez** [rust-cli/confy#87]
Hello, I'm using this crate in one project. The latest version of the crate depends on directories 4.0, but version 5.0.1 is the current version. Any thoughts on updating this dependency and other dependencies and publishing a new version of confy? I can send a PR with the dependency update and handle any API changes that might happen.

**Comment by matthiasbeyer** [comment]
I'd personally welcome a PR for that, yes!

**Comment by daniestevez** [comment]
PR sent. I've also updated the other dependencies. No code changes were needed.
