### ISSUE TITLE
serde-link fixed on master but wrong on docs.rs/confy

### ISSUE THREAD

**Issue by Ablesius** [rust-cli/confy#96]
Hi,

https://docs.rs/confy/0.3.1/src/confy/lib.rs.html#27 points to the non-existing `https://docs.rs/crates/serde`, but should link to the correct page (https://docs.rs/serde) since commit [40d9dfdf266fda310a52bf6c57798f0d71ae742e](https://github.com/rust-cli/confy/commit/40d9dfdf266fda310a52bf6c57798f0d71ae742e). I'm not sure what's wrong here, deployment wrong or something. I would have opened a PR but I am not sure there's anything to fix in the docs themselves.

Best,
Lexi

**Comment by deg4uss3r** [comment]
Hi Lexi! 

What you are seeing there is the documentation of the **specific version** `0.3.1`, if you go here: https://docs.rs/confy/latest/src/confy/lib.rs.html#27 you'll see the latest that points to the current version which does not 404 in the [rendered docs](https://docs.rs/confy/latest/confy/). 

That commit was included in the update to `0.5.0` so you must be on at least that version in the docs to see the change. 

```
$ git tag --contains 40d9dfd
0.5.0
0.5.1
v0.6.0
v0.6.1
```
